version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  ApplicationStart:
    - location: docker-compose up -d
      timeout: 300
      runas: root
  ApplicationStop:
    - location: docker-compose down
      timeout: 300
      runas: root
